; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; AMBIENTE 1: A CAIXA (ESP32 Padrão)
[env:caixa]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
; Filtra para compilar apenas a pasta Caixa
build_src_filter = +<Caixa/> 
lib_deps =
    arduino-libraries/Stepper@^1.1.3
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit SSD1306@^2.5.9

; =========================================

; AMBIENTE 2: A PULSEIRA (XIAO ESP32)
[env:pulseira]
platform = espressif32
; Se o seu for o XIAO S3, mude para: seeed_xiao_esp32s3
board = seeed_xiao_esp32c3 
framework = arduino
monitor_speed = 115200
; Filtra para compilar apenas a pasta Pulseira
build_src_filter = +<Pulseira/> 
lib_deps =
